"""Add trading models with correct index names

Revision ID: be5e36706f7d
Revises: 
Create Date: 2025-04-28 10:04:03.562132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5e36706f7d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('interval', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('taker_buy_volume', sa.Float(), nullable=False),
    sa.Column('taker_buy_quote_volume', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_symbol_interval_timestamp', 'candles', ['symbol', 'interval', 'timestamp'], unique=False)
    op.create_index(op.f('ix_candles_id'), 'candles', ['id'], unique=False)
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.Enum('SUPPORT', 'RESISTANCE', name='leveltype'), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('last_tested', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('volume_confirmation', sa.Float(), nullable=True),
    sa.Column('number_of_tests', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_levels', 'levels', ['symbol', 'is_active'], unique=False)
    op.create_index('idx_symbol_price', 'levels', ['symbol', 'price'], unique=False)
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('type', sa.Enum('LIMIT', 'MARKET', name='ordertype'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filled_quantity', sa.Float(), nullable=True),
    sa.Column('remaining_quantity', sa.Float(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_orders_order_id', 'orders', ['order_id'], unique=False)
    op.create_index('idx_orders_symbol_timestamp', 'orders', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('LEVEL_BOUNCE', 'LEVEL_BREAKOUT', 'TREND_CONTINUATION', 'VOLUME_SPIKE', 'MOMENTUM', name='signaltype'), nullable=False),
    sa.Column('strength', sa.Enum('WEAK', 'MEDIUM', 'STRONG', name='signalstrength'), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('volume_confirmation', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_signals_symbol_timestamp', 'signals', ['symbol', 'timestamp'], unique=False)
    op.create_index('idx_signals_valid', 'signals', ['symbol', 'is_valid'], unique=False)
    op.create_index(op.f('ix_signals_id'), 'signals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_id'), table_name='signals')
    op.drop_index('idx_signals_valid', table_name='signals')
    op.drop_index('idx_signals_symbol_timestamp', table_name='signals')
    op.drop_table('signals')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index('idx_orders_symbol_timestamp', table_name='orders')
    op.drop_index('idx_orders_order_id', table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_index('idx_symbol_price', table_name='levels')
    op.drop_index('idx_active_levels', table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_candles_id'), table_name='candles')
    op.drop_index('idx_symbol_interval_timestamp', table_name='candles')
    op.drop_table('candles')
    # ### end Alembic commands ###
